# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'beeper_example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for beeper_example
  pod 'beeper', :path => '../'
  pod 'Anchorage'

  target 'beeper_exampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'beeper_exampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
